### ISSUE TITLE
Please, add a config.php or a command to generate it

### ISSUE THREAD

**Issue by thdaguin** [vcian/php-db-auditor#11]
What's the structure of config.php ???
Help me...

**Comment by ruchit288** [comment]
@thdaguin 

For Database Configuration

Please refer to the file located at vendor/vcian/php-db-auditor/src/config.php.

**Comment by DylanDelobel** [comment]
Same issue I had to check here
I would add a little snippet into the README 🙏

**Comment by vc-bharat** [comment]
@DylanDelobel You can forge and generate a pull request for the same.
