### ISSUE TITLE
Unable to launch command

### ISSUE THREAD

**Issue by thdaguin** [vcian/php-db-auditor#7]
Could you be more specific about the installation ?

mkdir php-db-auditor
cd php-db-auditor
composer require vcian/php-db-auditor
php vendor/vcian/php-db-auditor/dbauditor

fails in : 
PHP Warning:  require(/home/totot/www/dixatable/vendor/vcian/php-db-auditor/vendor/autoload.php): Failed to open stream: No such file or directory in /home/toto/www/dixatable/vendor/vcian/php-db-auditor/dbauditor on line 3
PHP Fatal error:  Uncaught Error: Failed opening required '/home/toto/www/dixatable/vendor/vcian/php-db-auditor/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/toto/www/dixatable/vendor/vcian/php-db-auditor/dbauditor:3
Stack trace:
#0 {main}
  thrown in /home/toto/www/dixatable/vendor/vcian/php-db-auditor/dbauditor on line 3

**Comment by ruchit288** [comment]
@thdaguin  - Thanks for raising the issue.
We have resolved this error. A new change deployed in the latest version which is V2.0.0
